### ISSUE TITLE
Missing closing tag

### ISSUE THREAD

**Issue by hhabroad** [Harvester57/SpectreMeltdown-ADMX#1]
Hello Harvester57,

Firstly, thank you for this project, it will greatly simplify a long overdue security policy.  :)

I just wanted to let you know that there is a missing </stringTable> closing tag that needs to be added to the en-US/SpectreMeltdown.adml file to make the en-US/SpectreMeltdown.adml and SpectreMeltdown.admx files work correctly.  Without this line the Group Policy Editor throws an error.

I've attached my modified copy of the file for you with a .TXT extension.

All the best.
[SpectreMeltdown.adml.txt](https://github.com/Harvester57/SpectreMeltdown-ADMX/files/9443637/SpectreMeltdown.adml.txt)

**Comment by Harvester57** [comment]
Hi @hhabroad, thank you for reporting this bug.

The SpectreMeltdown ADMX template has been merged with my more general Security ADMX template, and I do not actively maintain it. Would you mind testing with the Security template (https://github.com/Harvester57/Security-ADMX) and let me know if you still have the bug ? 

I you really need the standalone version, I could update it to reflect the changes you suggested.

Best regards !

**Comment by Harvester57** [comment]
Ah, nevermind, should be fixed by commit https://github.com/Harvester57/SpectreMeltdown-ADMX/commit/95c5bf16bf4b9a921bd34591335faec5c2d01a93 :)

**Comment by hhabroad** [comment]
I've also tested the Security-ADMX as it may have some settings I'll need
to use in the future.

Thanks again!

**Comment by Harvester57** [comment]
Let me know if you have other suggestions or bugs to report ! :)
